name: deploy
on: 
    workflow_run: 
        workflows: build
        types: completed
jobs: 
    Deploying-to-Tomcat: 
        runs-on: ubuntu-latest
        environment: Test
        if: ${{ github.event.workflow_run.conclusion }} == 'success'
        steps: 
            - name: Downloading the artifact form Build
              uses: dawidd6/action-download-artifact@v2
              with:
                run_id: ${{ github.event.workflow_run.id }}
               # name: ${{ github.event.workflow_run.event.inputs.ARTIFACT_NAME }}
                path: ./artifacts
                search_artifacts: true
            - name: Deploying to Tomcat
              run: |
                echo "${{ github.event.workflow_run.conclusion }}"
                curl -v -u ${{secrets.TOMCAT_USR}}:${{secrets.TOMCAT_PSW}} -T /home/runner/work/spring-boot-jsp-postgres/spring-boot-jsp-postgres/artifacts/*/*.war http://34.125.70.121:8080/manager/text/deploy?path=/spring-demo-app-war
                
            