name: deploy
on: 
    workflow_run: 
        workflows: build
        types: completed
jobs: 
    Deploying-to-Tomcat: 
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion }} == 'success'
        steps: 
            - name: Downloading the artifact form Build
              uses: dawidd6/action-download-artifact@v2
              with:
                run_id: ${{ github.event.workflow_run.id }}
               # name: ${{ github.event.workflow_run.event.inputs.ARTIFACT_NAME }}
                path: ./artifacts
                search_artifacts: true
            - name: Deploying to Tomcat
              run: |
                ls
                cd */*/
                ls
                pwd
                
            